<?php $this->headLink()->prependStylesheet($this->baseUrl('/auth/css/module.css')) ?>

<div class="row">
  <div class="db_logotipo span7">
    <?php echo $this->partial('layouts/logotipo.phtml', 'auth') ?>
  </div>

  <div class="db_links span3">
    <ul>
      <li>
        <a href="<?php echo $this->baseUrl('/auth/login') ?>" title="<?php echo $this->translate->_('Login') ?>">
          <?php echo $this->translate->_('Login') ?>
        </a>
      </li>
      <li>
        <a href="<?php echo $this->baseUrl('/auth/nfse/autenticar') ?>"
           title="<?php echo $this->translate->_('Verificar NFSe') ?>">
          <?php echo $this->translate->_('Verificar NFSe') ?>
        </a>
      </li>
    </ul>
  </div>
</div>

<br>

<div class="row  span10">
  <div class="db_form">
    <fieldset>
      <legend class="text-error">
        <?php echo $this->translate->_('Cadastro para Prestador de Serviços Eventuais e Tomadores de Serviço') ?>
      </legend>
      <div class="alert alert-error">
        <strong><?php echo $this->translate->_('Atenção:') ?></strong>
        <?php
        echo $this->translate->_('Este cadastro é exclusivo para Prestadores de Serviços Eventuais e Tomadores de Serviço.');
        ?>
      </div>
      <?php echo $this->oForm ?>
      <div id="erros" class="db_form_error"></div>
    </fieldset>
  </div>
</div>