<?php if($this->administrativo) { ?>
<fieldset>
  <legend><?php echo $this->translate->_('Busca Contribuinte') ?></legend>
  
  <form class="form-horizontal" name="busca">
    <div class="control-group">
      <label class="control-label" for="im"><?php echo $this->translate->_('Inscrição Municipal:') ?></label>
      <div class="controls">
        <div class="input-append">
          <input type="text" id="im" name="im" />
          <button class="btn" id="buscador"><i class="icon-search"></i></button>            
        </div>
        <span class="help-block" id="status"></span>
      </div>
    </div>    
  </form>
</fieldset>
<?php } ?>

<fieldset>
  <legend><?php echo $this->translate->_('Parâmetros') ?></legend>
  
  <?php echo $this->form ?>
</fieldset>