<div class="db-header">
  <div class="db-header-logo-background"></div>
  <div class="db-seller-logo">
    <img class="pull-left" src="<?php echo $this->serverUrl('/global/img/logo_topo.png') ?>">

    <div class="db-header-logo-prefeitura">
      <div class="pull-left">
        <img height="74" width="64" src=<?php echo $this->serverUrl('/global/img/brasao.jpg') ?>>
      </div>

      <div class="db-header-nome-prefeitura">
        <?php echo $this->oPrefeitura->getNome() ?>
      </div>
    </div>
  </div>
</div>

