<?php if (!$this->lHtmlEmbutido) { ?>
  <html>
  <head>
<?php } ?>

  <style type="text/css">

    <?php if (!$this->lHtmlEmbutido) { ?>
    body {
      width: 1200px;
      margin: 0;
      font-size: 11px;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
    <?php } ?>

    table {
      border: solid 1px #000;
      text-align: center;
      border-collapse: collapse;
      width: 100%;
    }

    table tr td {
      border: solid 1px #000;
      text-align: left;
      padding-left: 5px;
    }

    table tr td.center {
      text-align: center;
    }

    table tr td.destacado {
      background-color: #DCDCDC;
    }

    table tr td.titulo {
      padding: 5px;
      font-weight: bold;
    }

    table tr td.imagem {
      padding: 10px;
      width: 120px;
      height: 120px;
    }

    .nfse_cancelada {
      position: absolute;
      width: 100%;
    }

    .nfse_cancelada_img {
      margin: 30% 10% 0;
    }

    .underline {
      text-decoration: underline;
    }
  </style>
</head>
<body>
<?php if ($this->oDadosNota->getIdNotaSubstituta()) { ?>
  <div class="nfse_cancelada">
    <img class="nfse_cancelada_img"
         src="<?php echo $this->baseUrl('/administrativo/img/nfse/tarja_substituida.png') ?>">
  </div>
<?php } else if ($this->oDadosNota->getCancelada()) { ?>
  <div class="nfse_cancelada">
    <img class="nfse_cancelada_img"
         src="<?php echo $this->baseUrl('/administrativo/img/nfse/tarja_cancelada.png') ?>">
  </div>
<?php } ?>

  <table>
    <tr>
      <td class="center imagem">
        <img src="<?php echo $this->baseUrl('/global/img/brasao.jpg') ?>" width="100px" height="100px">
      </td>
      <td colspan="4" class="center">
        <?php echo $this->oDadosPrefeitura->getNome() ?>
        <br>
        SECRETARIA MUNICIPAL DE FAZENDA - NOTA LEGAL
        <br>
        <span class="underline">NOTA FISCAL DE SERVIÇO ELETRÔNICA - NFSe</span>
      </td>
      <td class="center titulo">
        Número da
        <br>
        NFSe
        <br>
        <?php echo $this->oDadosNota->getNota() ?>
      </td>
    </tr>
    <tr>
      <td class="destacado">Data / Hora Emissão</td>
      <td class="center">
        <?php echo "{$this->oDadosNota->formatedData()} - {$this->oDadosNota->formatedHora()}" ?>
      </td>
      <td class="destacado">Competência</td>
      <td class="center"><?php echo str_pad($this->oDadosNota->getComp(), 7, 0, STR_PAD_LEFT) ?></td>
      <td class="destacado">Código de Verificação</td>
      <td class="center"><?php echo $this->oDadosNota->getCod_verificacao() ?></td>
    </tr>
    <tr>
      <td class="destacado">Número do RPS</td>
      <td class="center"><?php echo $this->oDadosNota->getN_rps() ?></td>
      <td class="destacado">Número da NFSe Substituida</td>
      <td class="center">
        <?php echo $this->oDadosNotaSubstituida ? $this->oDadosNotaSubstituida->getNota() : NULL ?>
      </td>
      <td class="destacado">Local da Prestação</td>
      <td class="center"><?php echo $this->oDadosNota->getServicoMunicipio() ?></td>
    </tr>
  </table>

  <br>

  <table>
    <tr>
      <td colspan="8" class="center destacado titulo">Dados do Prestador de Serviços</td>
    </tr>
    <tr>
      <td rowspan="7" class="center imagem">
        <?php if ($this->sLogoPrestador) { ?>
          <img alt="" width="100px" height="100px" src="<?php echo $this->baseUrl("/tmp/{$this->sLogoPrestador}") ?>">
        <?php } ?>
      </td>
      <td class="destacado">Razão Social</td>
      <td colspan="6"><?php echo $this->oDadosNota->getP_razao_social() ?></td>
    </tr>
    <tr>
      <td width="100px" class="destacado">Nome Fantasia</td>
      <td colspan="6"><?php echo $this->oDadosNota->getP_nome_fantasia() ?></td>
    </tr>
    <tr>
      <td class="destacado">CPF/CNPJ</td>
      <td><?php echo DBSeller_Helper_Number_Format::maskCPF_CNPJ($this->oDadosNota->getP_cnpjcpf()) ?></td>
      <td class="destacado">Inscrição Municipal</td>
      <td width="80px"><?php echo $this->oDadosNota->getP_im() ?></td>
      <td class="destacado">Inscrição Estadual</td>
      <td colspan="2"><?php echo $this->oDadosNota->getP_ie() ?></td>
    </tr>
    <tr>
      <td class="destacado">Município</td>
      <td colspan="6">
        <?php echo "{$this->oDadosNota->getPrestadorMunicipio()} / {$this->oDadosNota->getP_uf()}" ?>
      </td>
    </tr>
    <tr>
      <td class="destacado">Endereço</td>
      <td colspan="3"><?php echo $this->oDadosNota->getP_endereco() ?></td>
      <td class="destacado">CEP</td>
      <td colspan="2"><?php echo $this->oDadosNota->getP_cep() ?></td>
    </tr>
    <tr>
      <td class="destacado">Complemento</td>
      <td colspan="6"><?php echo $this->oDadosNota->getP_endereco_comp() ?></td>
    </tr>
    <tr>
      <td class="destacado">Telefone</td>
      <td><?php echo DBSeller_Helper_Number_Format::maskPhoneNumber($this->oDadosNota->getP_telefone()) ?></td>
      <td class="destacado">Email</td>
      <td colspan="4"><?php echo $this->oDadosNota->getP_email() ?></td>
    </tr>
  </table>

  <br>

  <table>
    <tr>
      <td colspan="6" class="center destacado titulo">Dados do Tomador de Serviços</td>
    </tr>
    <tr>
      <td class="destacado">Razão Social</td>
      <td colspan="5">
        <?php if ($this->oDadosNota->getT_razao_social()) { ?>
          <?php echo $this->oDadosNota->getT_razao_social() ?>
        <?php } else { ?>
          Não identificado
        <?php } ?>
      </td>
    </tr>
    <tr>
      <td class="destacado">CPF/CNPJ</td>
      <td><?php echo DBSeller_Helper_Number_Format::maskCPF_CNPJ($this->oDadosNota->getT_cnpjcpf()) ?></td>
      <td class="destacado">Inscrição Municipal</td>
      <td width="80px"><?php echo $this->oDadosNota->getT_im() ?></td>
      <td class="destacado">Município</td>
      <td>
        <?php if ($this->oDadosNota->getT_cnpjcpf()) { ?>
          <?php echo "{$this->oDadosNota->getTomadorMunicipio()} / {$this->oDadosNota->getT_uf()}" ?>
        <?php } ?>
      </td>
    </tr>
    <tr>
      <td class="destacado">Endereço</td>
      <td colspan="3"><?php echo $this->oDadosNota->getT_endereco() ?></td>
      <td class="destacado">CEP</td>
      <td><?php echo $this->oDadosNota->getT_cep() ?></td>
    </tr>
    <tr>
      <td class="destacado">Complemento</td>
      <td colspan="5"><?php echo $this->oDadosNota->getT_endereco_comp() ?></td>
    </tr>
    <tr>
      <td class="destacado">Telefone</td>
      <td><?php echo DBSeller_Helper_Number_Format::maskPhoneNumber($this->oDadosNota->getT_telefone()) ?></td>
      <td class="destacado">Email</td>
      <td colspan="3"><?php echo $this->oDadosNota->getT_email() ?></td>
    </tr>
  </table>

  <br>

  <table>
    <tr>
      <td colspan="4" class="center destacado titulo">Discriminação dos Serviços</td>
    </tr>
    <tr>
      <td colspan="4" height="130px" style="vertical-align: top">
        <?php echo $this->oDadosNota->getS_dados_discriminacao() ?>
      </td>
    </tr>
    <tr>
      <td colspan="4" class="center destacado titulo">Código do Serviço - Atividade</td>
    </tr>
    <tr>
      <td colspan="4">
        <?php
        echo "{$this->oDadosNota->getS_dados_item_lista_servico()} - {$this->oDadosNota->getDescricaoListaServico()}";
        ?>
      </td>
    </tr>
    <tr>
      <td colspan="4" class="center destacado titulo">CNAE - Descrição</td>
    </tr>
    <tr>
      <td colspan="4">
        <?php echo "{$this->oDadosNota->getS_dados_cod_cnae()}"; ?> -
        <?php
        $aServico = Contribuinte_Model_Servico::getByCodServico($this->oDadosNota->getS_dados_cod_tributacao());
        $oServico = reset($aServico);
        echo ($oServico instanceof Contribuinte_Model_Servico) ? $oServico->attr('desc_cnae') : NULL;
        ?>
      </td>
    </tr>
    <tr>
      <td colspan="4" class="center destacado titulo">Detalhamento Específico da Construção Civil</td>
    </tr>
    <tr>
      <td class="center destacado" width="200px">Código da Obra</td>
      <td class="center" width="200px"><?php echo $this->oDadosNota->getS_codigo_obra() ?></td>
      <td class="center destacado" width="200px">Código ART</td>
      <td class="center" width="200px"><?php echo $this->oDadosNota->getS_art() ?></td>
    </tr>
  </table>

  <br>

  <table>
    <tr>
      <td colspan="10" class="center destacado titulo">Tributos Federais</td>
    </tr>
    <tr>
      <td width="10%" class="destacado">PIS</td>
      <td width="10%">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_pis(), 2, 'R$ ') ?>
      </td>
      <td width="10%" class="destacado">COFINS</td>
      <td width="10%">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_cofins(), 2, 'R$ ') ?>
      </td>
      <td width="10%" class="destacado">IR</td>
      <td width="10%">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_ir(), 2, 'R$ ') ?>
      </td>
      <td width="10%" class="destacado">INSS</td>
      <td width="10%">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_inss(), 2, 'R$ ') ?>
      </td>
      <td width="10%" class="destacado">CSLL</td>
      <td width="10%">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_csll(), 2, 'R$ ') ?>
      </td>
    </tr>
  </table>

  <br>

<?php
$fRetencoesFederais = $this->oDadosNota->getS_vl_pis() + $this->oDadosNota->getS_vl_cofins();
$fRetencoesFederais += $this->oDadosNota->getS_vl_ir() + $this->oDadosNota->getS_vl_inss();
$fRetencoesFederais += $this->oDadosNota->getS_vl_csll();
?>

  <table>
    <tr>
      <td colspan="2" class="center destacado titulo" width="200px">
        Detalhamento de Valores - Prestador dos Serviços
      </td>
      <td colspan="2" class="center destacado titulo">Outras Retenções</td>
      <td colspan="2" class="center destacado titulo">Calculo do ISSQN devido no Município</td>
    </tr>
    <tr>
      <td class="destacado" width="150px">Valor dos Serviços</td>
      <td width="150px">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_servicos(), 2, 'R$ ') ?>
      </td>
      <td colspan="2" class="destacado center">Natureza Operação</td>
      <td class="destacado center" width="180px">Valor dos Serviços</td>
      <td width="120px">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_servicos(), 2, 'R$ ') ?>
      </td>
    </tr>
    <tr>
      <td class="destacado">(-) Desconto Incondicionado</td>
      <td>
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_desc_incondicionado(), 2, 'R$ ') ?>
      </td>
      <td colspan="2" class="center">
        <?php echo Contribuinte_Model_NaturezaOperacao::getById($this->oDadosNota->getNatureza_operacao()) ?>
      </td>
      <td class="destacado">(-) Deduções permitidas em lei</td>
      <td>
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_deducoes(), 2, 'R$ ') ?>
      </td>
    </tr>
    <tr>
      <td class="destacado">(-) Desconto Condicionado</td>
      <td>
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_condicionado(), 2, 'R$ ') ?>
      </td>
      <td colspan="2" class="destacado center">Regime especial Tributação</td>
      <td class="destacado">(-) Desconto Incondicionado</td>
      <td>
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_desc_incondicionado(), 2, 'R$ ') ?>
      </td>
    </tr>
    <tr>
      <td class="destacado">(-) Retenções Federais</td>
      <td>
        <?php echo DBSeller_Helper_Number_Format::toMoney($fRetencoesFederais, 2, 'R$ ') ?>
      </td>
      <td colspan="2" class="center"><?php echo $this->oPrestador->getDescricaoRegimeTributario() ?></td>
      <td class="destacado">Base de Cálculo</td>
      <td>
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_bc(), 2, 'R$ ') ?>
      </td>
    </tr>
    <tr>
      <td class="destacado">(-) Outras Retenções</td>
      <td>
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_outras_retencoes(), 2, 'R$ ') ?>
      </td>
      <td colspan="2" class="destacado center">Opção Simples Nacional</td>
      <td class="destacado">(x) Alíquota %</td>
      <td>
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_aliquota(), 2, '', '%') ?>
      </td>
    </tr>
    <?php if ($this->oDadosNota->getS_dados_iss_retido() == Contribuinte_Model_Nota::TOMADOR_RETEM_ISS) { ?>
      <tr>
        <td class="destacado">(-) ISS</td>
        <td>
          <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_iss(), 2, 'R$ ') ?>
        </td>
        <td colspan="2" class="center"><?php echo $this->oPrestador->getDescricaoOptanteSimples() ?></td>
        <td class="destacado">ISS à reter</td>
        <td>(x) Sim () Não</td>
      </tr>
    <?php } else { ?>
      <tr>
        <td class="destacado">(-) ISS</td>
        <td><?php echo DBSeller_Helper_Number_Format::toMoney(0, 2, 'R$ ') ?></td>
        <td colspan="2" class="center"><?php echo $this->oPrestador->getDescricaoOptanteSimples() ?></td>
        <td class="destacado">ISS à reter</td>
        <td>() Sim (x) Não</td>
      </tr>
    <?php } ?>
    <tr>
      <td class="destacado" rowspan="2">(=) Valor Líquido</td>
      <td rowspan="2">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getVl_liquido_nfse(), 2, 'R$ ') ?>
      </td>
      <td colspan="2" class="destacado center">Incentivador Cultura</td>
      <td class="destacado" rowspan="2">(=) Valor do ISS</td>
      <td rowspan="2">
        <?php echo DBSeller_Helper_Number_Format::toMoney($this->oDadosNota->getS_vl_iss(), 2, 'R$ ') ?>
      </td>
    </tr>
    <tr>
      <td class="center">2 - Não</td>
    </tr>
  </table>

  <br>

<?php
if ($this->oDadosPrefeitura->getInformacoesComplementaresNfse() ||
  $this->oDadosNota->getS_informacoes_complementares()
) {
  ?>
  <table>
    <tr>
      <td class="center titulo">Avisos</td>
      <td>
        <?php echo $this->oDadosPrefeitura->getInformacoesComplementaresNfse() ?>
        <br>
        <?php echo $this->oDadosNota->getS_informacoes_complementares() ?>
      </td>
    </tr>
  </table>
<?php } ?>

<?php if (!$this->lHtmlEmbutido) { ?>
  </body>
  </html>
<?php } ?>